version: '3.8'

services:
  dev:
    build: .
    container_name: dev_container
    volumes:
      - ~/.ssh:/home/devuser/.ssh
    ports:
      - "2222:22"
      - "8080:8080"
    environment:
      - GITHUB_REPO=https://github.com/ricklon/gpt4vision-streamlit
      - GIT_USER_NAME=ricklon
      - GIT_USER_EMAIL=rick.rickanderson@gmail.com
    command: /bin/bash -c "service ssh start && su devuser -c 'code-server --bind-addr 0.0.0.0:8080'"
